from pathlib import Path
P=Path(__file__).parent
marker='Fictional restaurant concept · Sample content · No live services.'
def start(title,cls):
 return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="{title}: an independent, fictional restaurant design study. No live services."><title>{title} — Restaurant studies II</title><link rel="icon" href="assets/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="styles.css"><script src="interactions.js" defer></script></head><body class="{cls}"><a class="skip" href="#main">Skip to content</a><div class="concept-marker">{marker}</div>'''
def header(name,num):
 return f'''<header class="masthead"><a href="index.html" class="back" aria-label="Back to concept gallery">← THE COLLECTION</a><span class="wordmark">{name}</span><span class="edition">STUDY {num} / 03</span></header>'''
def actions(primary='Menu',request='Reservation request'):
 return f'''<nav class="tasks" aria-label="Restaurant essentials"><a class="primary" href="#menu">{primary} <span aria-hidden="true">↗</span></a><a href="#hours">Hours</a><a href="#phone">Call <small>— sample</small></a><a href="#address">Directions <small>— sample</small></a><a href="#requests" data-request="{request}">{request} <small>— sample</small></a><a href="#requests" data-request="Catering request">Catering request <small>— sample</small></a></nav>'''
def visit():
 return '''<section class="visit" aria-labelledby="visit-heading"><div><p class="eyebrow">Before you visit</p><h2 id="visit-heading">The practical things.</h2></div><dl><div id="hours" tabindex="-1"><dt>Hours</dt><dd>Not set for this concept.<br>No opening hours are represented.</dd></div><div id="phone" tabindex="-1"><dt>Phone / call</dt><dd>No phone number is connected.<br>This sample does not place a call.</dd></div><div id="address" tabindex="-1"><dt>Address / directions</dt><dd>No physical location.<br>No map or directions are connected.</dd></div></dl></section>'''
def requests(types):
 return f'''<section id="requests" class="requests" tabindex="-1" aria-labelledby="requests-heading"><p class="eyebrow">A preview, not a service</p><h2 id="requests-heading">An invitation to imagine.</h2><p>{types} are sample pathways only. No live ordering, reservations or catering are offered here. Nothing can be submitted, purchased or confirmed.</p><p>Explore the menu and the mood. This table exists only on the page.</p><a href="#menu">Return to the sample menu ↑</a></section>'''
def end(nextpage,nextname):
 return f'''<footer><p>Restaurant studies II <span aria-hidden="true">/</span> Tushar Nova</p><a href="{nextpage}.html">Next: {nextname} →</a><small>{marker}</small></footer><dialog aria-labelledby="dialog-title" aria-describedby="dialog-copy"><button class="close" type="button" autofocus>Close <span aria-hidden="true">×</span></button><p class="eyebrow">Concept interaction</p><h2 id="dialog-title">Sample request</h2><p id="dialog-copy">This is a fictional service pathway. No provider or inbox is connected. Nothing is sent, ordered or reserved.</p><p>In a real restaurant site, this action would connect to its verified service.</p></dialog></body></html>'''
def img(cls='',loading='eager'):
 return f'''<img class="{cls}" src="assets/table-960.webp" srcset="assets/table-640.webp 640w, assets/table-960.webp 960w" sizes="(max-width: 700px) 100vw, 60vw" width="960" height="640" loading="{loading}" alt="Illustrated table with roasted carrots, flatbread, leafy greens, pears and a candle; fictional food artwork.">'''
quiet=start('Quiet Editorial','quiet')+header('Quiet Editorial','01')+'''<main id="main"><div class="quiet-top"><p class="eyebrow">An imagined dining room · An unhurried evening</p>'''+actions()+'''</div><section class="editorial-hero" aria-labelledby="hero-heading"><figure>'''+img()+'''<figcaption>01 / A table in warm light. Original AI-generated concept illustration.</figcaption></figure><div class="editorial-title"><p class="eyebrow">Pull up a chair</p><h1 id="hero-heading">An evening,<br><em>unhurried.</em></h1><p>A little candlelight. Something to share.<br>Room for the conversation to wander.</p></div><div class="margin-note"><span>THE ART OF<br>STAYING A LITTLE</span><i aria-hidden="true">↓</i></div></section>'''+visit()+'''<section id="menu" class="editorial-menu" aria-labelledby="menu-heading"><header><p class="eyebrow">01 — At the table</p><h2 id="menu-heading">A few good<br><em>things.</em></h2><p>A fictional menu sketch.<br>No prices or dietary claims.</p></header><div class="menu-columns"><section><h3>To begin</h3><article><h4>Warm flatbread</h4><p>Torn edges, a small dish of herb oil.</p></article><article><h4>Leaf &amp; stem</h4><p>A tangle of greens with a bright citrus dressing.</p></article></section><section><h3>To linger over</h3><article><h4>Ember carrots</h4><p>Roasted roots, a soft cream, a scattering of herbs.</p></article><article><h4>Pear at the close</h4><p>Poached pear with a spoonful of vanilla cream.</p></article></section><p class="menu-note">Imagined dishes and descriptions, not an available restaurant menu.</p></div></section><aside class="editorial-note"><p class="eyebrow">A note on the mood</p><p>Not every evening<br>needs an <em>occasion.</em></p><span>Fictional atmosphere study — linen, low light, a table for two.</span></aside>'''+requests('Reservation and catering requests')+'''<div class="secondary-action"><a href="#requests" data-request="Catering request">Catering request — sample ↗</a></div></main>'''+end('night-market','Night Market')
(P/'quiet-editorial.html').write_text(quiet)
night=start('Night Market','night')+header('NIGHT / MARKET','02')+'''<main id="main"><section class="market-opening" aria-labelledby="hero-heading"><div class="market-title"><p class="eyebrow">An imaginary corner of the night</p><h1 id="hero-heading">GOOD FOOD.<br><span>LOUD TABLE.</span></h1></div><div class="market-ticket"><span class="ticket-star" aria-hidden="true">✳</span><p>YOUR NEXT BITE<br>STARTS HERE.</p><small>Sample menu / No live orders</small></div></section>'''+actions('Explore menu','Order request')+'''<div class="ticker" aria-label="Market mood: pass the plates, share the table"><span>PASS THE PLATES</span><b aria-hidden="true">✳</b><span>SHARE THE TABLE</span><b aria-hidden="true">✳</b><span>STAY FOR ONE MORE STORY</span></div><section id="menu" class="market-menu" aria-labelledby="menu-heading"><header><p class="eyebrow">The menu board / Fictional dishes</p><h2 id="menu-heading">PICK YOUR MOOD.</h2><div class="filters" aria-label="Filter sample menu" hidden><button type="button" data-filter="all" aria-pressed="true">Everything</button><button type="button" data-filter="plates" aria-pressed="false">Plates</button><button type="button" data-filter="sips" aria-pressed="false">Sips</button></div><p class="filter-status" role="status" aria-live="polite">4 sample dishes &amp; drinks. No prices or dietary claims.</p></header><div class="board"><article data-category="plates"><span class="dish-number">01</span><div><h3>CHARRED &amp; BRIGHT</h3><p>Ember carrots, herb cream, a squeeze of citrus.</p></div><span class="dish-tag">PLATE</span></article><article data-category="plates"><span class="dish-number">02</span><div><h3>TEAR &amp; SHARE</h3><p>Warm flatbread with a little bowl of herb oil.</p></div><span class="dish-tag">PLATE</span></article><article data-category="plates"><span class="dish-number">03</span><div><h3>THE GREEN THING</h3><p>Leafy greens, crisp radish, citrus dressing.</p></div><span class="dish-tag">PLATE</span></article><article data-category="sips"><span class="dish-number">04</span><div><h3>CITRUS AFTER DARK</h3><p>Orange, sparkling water, a sprig of rosemary.</p></div><span class="dish-tag">SIP</span></article></div></section>'''+visit()+'''<section class="market-after" aria-labelledby="after-heading"><div><p class="eyebrow">From the imaginary kitchen</p><h2 id="after-heading">A LITTLE HEAT.<br>A LOT TO SHARE.</h2><p>A concept for quick decisions and long conversations.</p><a href="#requests" data-request="Catering request">Catering request — sample ↗</a></div><figure>'''+img(loading='lazy')+'''<figcaption>Illustration only. AI-generated concept artwork.</figcaption></figure></section>'''+requests('Order and catering requests')+'''</main>'''+end('garden-table','Garden Table')
(P/'night-market.html').write_text(night)
garden=start('Garden Table','garden')+header('garden table','03')+'''<main id="main"><section class="garden-welcome" aria-labelledby="hero-heading"><div class="garden-copy"><p class="eyebrow">An imagined neighbourhood gathering place</p><h1 id="hero-heading">A little space.<br>A shared <em>table.</em></h1><p>For the everyday pleasure<br>of eating together.</p>'''+actions('Sample menu','Table request')+'''</div><figure class="garden-art">'''+img()+'''<figcaption>A table imagined, not a real venue.<br>AI-generated concept illustration.</figcaption></figure></section>'''+visit()+'''<section class="garden-menu" id="menu" aria-labelledby="menu-heading"><div class="garden-menu-title"><span class="seed" aria-hidden="true">❋</span><p class="eyebrow">A small, fictional menu</p><h2 id="menu-heading">Something<br>for the table.</h2><p>A handful of imagined dishes.<br>No prices or dietary claims.</p></div><div class="garden-courses"><details open><summary>Start with a little <span aria-hidden="true">+</span></summary><div><h3>Warm flatbread</h3><p>Tear, dip, pass along. Served with herb oil.</p><h3>Leaf &amp; stem</h3><p>Greens and radish with a citrus dressing.</p></div></details><details><summary>Share something warm <span aria-hidden="true">+</span></summary><div><h3>Ember carrots</h3><p>Roasted roots with herb cream.</p><h3>A bowl of the season</h3><p>An imagined vegetable broth with soft grains.</p></div></details><details><summary>Stay for something sweet <span aria-hidden="true">+</span></summary><div><h3>Pear &amp; vanilla</h3><p>Poached pear, vanilla cream, a quiet finish.</p></div></details></div></section><section class="garden-gather" aria-labelledby="gather-heading"><div class="drawn-flower" aria-hidden="true">✳</div><div><p class="eyebrow">Room for your people</p><h2 id="gather-heading">Bring a few<br>familiar faces.</h2><p>An imagined place for catching up, passing plates, and making an ordinary day feel good.</p><a class="pill" href="#requests" data-request="Group and catering request">Group &amp; catering request — sample ↗</a></div></section>'''+requests('Table, group and catering requests')+'''</main>'''+end('quiet-editorial','Quiet Editorial')
(P/'garden-table.html').write_text(garden)
index=start('Three tables. Three different stories.','gallery')+'''<header class="gallery-header"><a href="index.html" class="wordmark">TUSHAR NOVA</a><span class="eyebrow">Restaurant studies / Volume II</span></header><main id="main"><section class="gallery-intro"><p class="eyebrow">The comparison collection · 2026</p><h1>Three tables.<br><em>Three different stories.</em></h1><p>One simple idea: a restaurant should feel like itself.<br>Explore three distinct ways to welcome someone in.</p></section><div class="concept-grid"><a class="concept-card card-quiet" href="quiet-editorial.html"><div class="card-preview"><span class="mini-label">01 / QUIET EDITORIAL</span><span class="mini-quiet-title">An evening,<br><i>unhurried.</i></span>'''+img()+'''</div><div class="card-caption"><h2>Quiet Editorial <span aria-hidden="true">↗</span></h2><p>Warm, asymmetrical, quietly expressive.</p><small>A magazine spread · Open menu · Reservation pathway</small></div></a><a class="concept-card card-night" href="night-market.html"><div class="card-preview"><span class="mini-label">02 / NIGHT MARKET</span><strong>GOOD<br>FOOD.<br><i>LOUD<br>TABLE.</i></strong><span class="mini-strip">PASS THE PLATES ✳ SHARE THE TABLE</span></div><div class="card-caption"><h2>Night Market <span aria-hidden="true">↗</span></h2><p>Bold type. Fast choices. A little noise.</p><small>A menu board · Category filters · Order pathway</small></div></a><a class="concept-card card-garden" href="garden-table.html"><div class="card-preview"><span class="mini-label">03 / GARDEN TABLE</span><span class="mini-garden-title">A little space.<br>A shared <i>table.</i></span>'''+img()+'''</div><div class="card-caption"><h2>Garden Table <span aria-hidden="true">↗</span></h2><p>Soft edges and space to settle in.</p><small>An organic composition · Course accordions · Group pathway</small></div></a></div><section class="gallery-note"><h2>Made to compare. Easy to explore.</h2><p>Every concept puts the menu, hours and contact pathways within easy reach. The food, atmosphere and service pathways are fictional. No live calls, directions, orders or bookings.</p><p>Shared original AI-generated artwork from the first showcase; new page structures, compositions and interactions.</p></section></main><footer><p>Restaurant studies II / Tushar Nova</p><small>Fictional restaurant concept · Sample content · No live services.</small></footer></body></html>'''
(P/'index.html').write_text(index)
